# Generated by Django 5.0.6 on 2024-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('overview', models.TextField()),
                ('poster', models.URLField(max_length=1000)),
                ('banner', models.URLField(max_length=1000)),
                ('genre', models.CharField(max_length=1000)),
            ],
        ),
    ]
